name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build with Docker Compose
        run: docker-compose -f docker-compose.yml build   

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Start services with Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      - name: Stop services
        run: docker-compose -f docker-compose.yml down
